language: node_js
node_js:
  - "stable"
deploy:
  provider: heroku
  api_key:
    secure: qeIliGCAo/ZnAp3WvHzN+wMravIKZ9GROyhedgVbBLY3XMB8MINudGInQvxSc/shz57yhfZWwK3weCBmvnTKgiEsWCv7Y5cWI0mT4Q4g0z79hX/p0jv1YZRHKcz+jLIuaKlhWdYZ9uLt1IIBWLIrZEDqT1TLx40gxOayVC5hA/EDi4ZbaZvybOZ7FldHdSXIPKzw+vSB27IjN5O5OzlSJxYloozT0RTzie1Wca3ybc7L12qz+4q2s9g9jPHnhBcCoB950JOgBkel/YoB7my8xzx3A+VK6N6P6kd+vzO40fkZVNIrAklRPRQcA8XXI9oXkRXwBpKiuT5jYVYWFcJf8DOEWY3wqmmjcY+61G3sQH4u+JbVag/wHJXcwKqMXTL6obu9YCYwv7VxdVymyAHKxaVMbrqeCsjtSpEMwjkdGycf+P5V/OhDyEh+o+XsLVcp1AMK5VnucC7UujatruBdwHFn0lIGjMfVe1evXIlj/cWPT4WOd2dsfcnJ1WrPszbpxMZSIcJ62WwleJbKTBXpR94fcKY/N2WHUx8lLXlL5DkOVvmzRjCqo3Kdtmjd+6aZvwXKVhMq4fwVM0VXWxpTE+xwe/3ATeXid1IK0IlJcfCY6watjHVEQBIN/gTKlocgKNxDm2VcVhFPgigUXQlLPLrtvT3X481JdRppNZKUbu8=