language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  app: node-chat-uwu
  api_key:
    secure: eqR2hlZAObPT3teV7BGH4EqL4Qpf6OKqQc7Pwacsf3o24E8UPOT5EmljJOXgoeQFQIE7nZ5xPDfMGIXdLjAmHZ9fCSSJZnyuO470BRAkNiGjsWAoGW6nmF6bUeyQYcKnSns3VO1dTE6aexHNhmflXMMsPTqm3hRQ+FKjj3ksn6vinXtZHpKn03rO729ai/EzeKRiiSITuCE26dCZ/5BiQODgSHvwI40/TSdWuNW/oawQIjdJS1u0PtIGSp+Ywk0C7ta2sjgMc5uLANqc4RNU+twssY7Y0OLR6fzKogvc8QDiVgDxYx5jJo4JEbqoR+x8mB9GEgKBQAlw6Z9oj3FR4KhhkrauvE3jmmlfDwjJDUFwK6FJsPfRTgaXJbumsco2ZoNs1CBGVd2KgkmTcnnlG2yIbN4//yuDLCC4cAR0tXlUFOaPsGb7WsMA+cvmhYRISDOE2cTvbTBG+3I38BE2GbSkm+131nNaxTlt5fT/R4F4Lu8yi+axoUxf2+4ngLShAQ7ahssbJRzMt1tMyX+AHMzA9EVWqdWsckkobVPIA8py9ZZ0xGSbooshbi49VpSw5F6yZ6reOQDgt87RrgkV51EhJ8+H/DHXb1VsmjUS3xel0k664a8dfMyBn9hogNHPaTfHL1aNIfSt9LnjDgPs7V+U0jsiXbb+WJQ6M1I0g7A=
