language: node_js
node_js:
- stable
deploy:
  provider: heroku
  api_key:
    secure: "VnR4X7gRh7bq9FrK/ZbEvFpfpKWQ7iU8kzrmdBHUJ/+xOvY6T/7JW6h3b0kmZF9D6vLQ6o+rWUJika7eDdXMPcC23fzA8J1lrwBQOXG99RntOyPFYLkNoug54ZgNzVT4LRYZnxy94OXHHxa0boyBRR1keknAd1CCHswDy5jVt/oyRyRjbloZdjJLPtLDbePD7giArdmrIz7geY8KveQ7EnPlIuvHQHf+Tn7r7/lO0SKkDrHBhIXfurfrA4NlfYZmtq0ElVxBrk4FK4yANTwqspDVkVqbUaYKjtm1mPtT3lV63GF/zvY+R5Yj2Omhl/hZrpAcDUjLfrzgiCMhmi5BlfAaieVnjMgWdSlHSjGRaUYkAOq4oeHJpxKv8/xvTqvbDVVUhmKuxZE0annPfvlJYPfvBi8CAlYSRrufHGHGf+O4gT48SM/A1o/3f2MhgWsXO0ZZK+oURp5qkxMmfRiGIehi4OoxcrDVk6YEfxjVleMiCshaL+ILWesvrF6UzB3PCAUrkkWzwo7z2Zx4C6ZktCJAyLWzeebpAF8GuPKl9CqqVVmXRrh4b9Ib56s4RBy3I4vYHgU6rBcYLMHWFlS5mVZV7sj5pOGOxxpxUuzXEm1Pg8w3RGSFJnTj6FqG4vZnR0zJXIr1/luMS6/Z/p8oy3PMWbDJ1Ft/52P+Xmqzx4s="