language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: DHfk1Km+1qU7KBkGs2stBoogP5x8Ws8/SYnhG2kL1tIzlhkmpec9HWvwSNBjLC9BlIjyd1S4JzIIVy1U4J723LkQRbV5QRXQ007GM7EoKc9YytlsslfX7W14PG9mGN+fc/S0kzt8sMy1biKb7ILxQHI2ttM2CjpVRA0+Ee93bIKSFQ554X7+9V1NfYsFzRd/ftc7qTVu1duFjqCDaxsqoi0AT+5aheAsqZEKGI0r5zRmOhx+qtCGznnItAdZn3BF7PWeu6UclSBBxQ628QlLczr9VlmM9/W8u2AgNeJBT/U1pFhP2c3I0FARqgIZIPDInj3SWWWL9E5gcoqer5wqUBFX8MetPwX16cjhzlmYARr6jNw1S6Q6lVraSUVSiX2N/BFfMdy8CuSfQAELOGwhreHdhbUqUCL2d4sWu+lQbq8WaFn46Pt+8bn1BozMMpLDo9r9lRHI++phi0evfQokVZ2EzejNLVBEkXERu9s2Pk+XocHpKecAb39TWNCEEUMf4NcmixBOqq8M/KqQ8ZDwLNS+NijehepL9y8Fdoobi1itqdSwzVmgFehSYHTUy+mxwjG181YpwN3nUuugQAbH46Gs4dZjOiqMMqPVS/VZGRQGcN04ct3qS3FgooWa/v/7OvZdR2PeH51E3qWFrftRsz+XO857dz2GnPTJIH2r7Bw=
