language: node_js
node_js:
- stable
deploy:
  provider: heroku
  api_key:
    secure: CyixtIFlq7Z3wVwy46vJNQNgsAlUXZGmQuKQ853owQ/fSitudKyFeOeUxm3S8SRBcJ/Js5JAiVcyqo5300B7DzybQwR1JORRpCEDu8aYspACX9eTPsk2fetUiuzlF5J2llGprfyZw4afmsw9zLjDWkO2exmKZHPemaOnawXCppprqDZXECisNkLm9M9e2VcTkrVAwiJaYp6MGTro60GCuobhMlFxSxd5tNfyKSeE0X8k7jn8Gpbus4Yo+0DV6HmNS6JY9vRBemnx9PTYjQ5X3n/NxMGxmEBAI/CB4Xenw8dvMIX4KOwZ49WArh9SBzUQ+EzorXeg7Pp2an07N2OIZKI8SyWrraJp6/sdKpRC14f9KZUCbAQDYYac1k/JAFycity9iFTQAe1aJHDAcZxXAiD8dd//FQPjgTgBJUc+3Q98pBKQEBsC1evgOMxfZE/6iSlwVrATrtJlk3VyOVWvHLkP9U3GHlYGoGH8yfN7bq0pmPlSaDM4xxH8NAWFxxNuT80OUa8x+jXknmLaC0bqLg8ap/TJZpOjakfL+RqSlBu0w5xOd7cESz8h8PVfFKNx6OoddJe1fFCJco7T26ys3yH/+Hq9hc0lCor9yIkHjiqXn7VkeqgKTByWS6rLoNIFvaIqR5z/iYO/uiQ0R8TvO9zwKWN7D0UAJ4iH1Xc0Esw=